/**
 * Core types for the US federal tax engine.
 *
 * Design notes:
 * - All monetary values are plain `number` in whole dollars-and-cents (e.g. `1234.56`).
 *   Tax computation is done in floating point and rounded only at the boundary, which
 *   mirrors how IRS worksheets behave. Use {@link roundCents} on anything you display.
 * - Every parameter set is keyed by tax year and carries its own citations, so a
 *   consumer can always trace a number back to the Revenue Procedure it came from.
 */

/** IRS filing status. */
export type FilingStatus =
  | 'single'
  | 'marriedFilingJointly'
  | 'marriedFilingSeparately'
  | 'headOfHousehold'
  | 'qualifyingSurvivingSpouse';

export const FILING_STATUSES: readonly FilingStatus[] = [
  'single',
  'marriedFilingJointly',
  'marriedFilingSeparately',
  'headOfHousehold',
  'qualifyingSurvivingSpouse',
];

/**
 * One marginal rate band.
 *
 * `upTo` is the *upper* bound of taxable income for this band (inclusive in the
 * sense that income at exactly `upTo` is still taxed at `rate`). The final band
 * uses `Infinity`.
 */
export interface Bracket {
  readonly rate: number;
  readonly upTo: number;
}

/** Per-band detail returned alongside a bracket computation. */
export interface BracketDetail {
  readonly rate: number;
  /** Amount of taxable income falling inside this band. */
  readonly incomeInBracket: number;
  /** Tax generated by this band. */
  readonly tax: number;
}

export interface IncomeTaxResult {
  readonly taxableIncome: number;
  readonly tax: number;
  /** Rate applied to the next dollar of ordinary income. */
  readonly marginalRate: number;
  /** `tax / taxableIncome`, or 0 when there is no taxable income. */
  readonly effectiveRate: number;
  readonly brackets: readonly BracketDetail[];
}

export interface SelfEmploymentTaxResult {
  /** Net profit multiplied by {@link YearParameters.seNetEarningsFactor}. */
  readonly netEarnings: number;
  /** 12.4% OASDI portion, capped by the Social Security wage base. */
  readonly socialSecurity: number;
  /** 2.9% Medicare portion, uncapped. */
  readonly medicare: number;
  /** `socialSecurity + medicare` — the Schedule SE total. */
  readonly total: number;
  /**
   * The above-the-line deduction for one half of SE tax.
   *
   * Note this is half of the Schedule SE total only. Additional Medicare Tax
   * (Form 8959) is *not* deductible and is not included here.
   */
  readonly deductibleHalf: number;
  /** True when net earnings fell below the $400 filing floor, so no SE tax is due. */
  readonly belowThreshold: boolean;
}

export interface FicaSide {
  readonly socialSecurity: number;
  readonly medicare: number;
  readonly total: number;
}

export interface FicaResult {
  readonly employee: FicaSide & { readonly additionalMedicare: number };
  /** Employers match OASDI and Medicare but never pay Additional Medicare Tax. */
  readonly employer: FicaSide;
}

export interface CapitalGainsResult {
  readonly tax: number;
  readonly brackets: readonly BracketDetail[];
}

/** A citation for a parameter set, so numbers are always traceable. */
export interface Citation {
  readonly title: string;
  readonly url: string;
}

/**
 * A phase-out expressed in whole increments of income above a threshold.
 *
 * The OBBBA deductions all phase out this way, but they do *not* round the same
 * direction, and the direction is worth real money at the margin:
 *
 * - §224 (tips) and §225 (overtime) reduce by `$100` for each **full** `$1,000`
 *   of excess, so partial increments are dropped (`rounding: 'down'`).
 * - §163(h)(4) (vehicle loan interest) reduces by `$200` for each `$1,000`
 *   **"or portion thereof"**, so a single excess dollar costs a full `$200`
 *   (`rounding: 'up'`).
 */
export interface SteppedPhaseOut {
  /** Reduction applied per counted increment. */
  readonly amountPerIncrement: number;
  /** Size of one increment of excess income. */
  readonly increment: number;
  /** How a partial increment is counted. */
  readonly rounding: 'down' | 'up';
  /** MAGI above which the phase-out begins, by filing status. */
  readonly thresholds: Readonly<Record<FilingStatus, number>>;
}

/**
 * The four temporary deductions created by the One Big Beautiful Bill Act
 * (Pub. L. 119-21) and reported on Schedule 1-A (Form 1040).
 *
 * All four are available whether or not the filer itemizes, but none of them is
 * an *adjustment to income* — they are claimed below AGI, on Form 1040 line 13b.
 * That distinction matters: they do not reduce the AGI or the MAGI that drives
 * their own phase-outs, the NIIT threshold, or anything else keyed to AGI.
 *
 * Every one of them is scheduled to expire after tax year 2028.
 */
export interface ScheduleOneAParameters {
  /** Last tax year in which these deductions are available. */
  readonly finalYear: number;
  readonly tips: {
    /** Cap per *return* — it is not doubled on a joint return. */
    readonly cap: number;
    readonly phaseOut: SteppedPhaseOut;
  };
  readonly overtime: {
    /** Cap per return, doubled only for married filing jointly. */
    readonly cap: Readonly<Record<FilingStatus, number>>;
    readonly phaseOut: SteppedPhaseOut;
  };
  readonly senior: {
    /** Amount per eligible individual — the filer, plus the spouse on a joint return. */
    readonly amountPerEligibleIndividual: number;
    readonly ageThreshold: number;
    /**
     * Fraction of the MAGI excess by which each individual's amount is reduced.
     * Unlike the other three, this is a continuous rate with no rounding.
     */
    readonly phaseOutRate: number;
    readonly phaseOutThreshold: Readonly<Record<FilingStatus, number>>;
  };
  readonly vehicleLoanInterest: {
    readonly cap: number;
    readonly phaseOut: SteppedPhaseOut;
  };
  /**
   * Filing statuses barred from every one of these deductions.
   *
   * §224(f) and §225(e) each say the section applies to a married individual only
   * if a joint return is filed; the senior deduction and the vehicle loan interest
   * deduction carry the same restriction per IRS guidance.
   */
  readonly ineligibleFilingStatuses: readonly FilingStatus[];
}

/**
 * The § 164(b)(6) cap on state and local tax deductions.
 *
 * OBBBA § 70120 raised the cap from $10,000 to $40,000 for 2025 and 1% more each
 * year through 2029, then added something the $10,000 cap never had: a **phase-down**.
 * Above the threshold the cap is reduced by 30 cents per dollar of MAGI, but never
 * below the floor.
 *
 * The effect is a band of income in which the marginal rate is far higher than the
 * bracket suggests — losing 30 cents of deduction per dollar earned at a 35% rate
 * is an extra 10.5 points — and then a return to normal once the floor is reached.
 * That non-monotonic marginal rate is the whole point of modelling this.
 */
export interface SaltCapParameters {
  /** Last tax year of the raised cap. It reverts to $10,000 / $5,000 after this. */
  readonly finalYear: number;
  /** The cap before any phase-down, by filing status. */
  readonly cap: Readonly<Record<FilingStatus, number>>;
  /** Cents of cap lost per dollar of MAGI above the threshold. */
  readonly phaseDownRate: number;
  readonly phaseDownThreshold: Readonly<Record<FilingStatus, number>>;
  /** The cap can never be phased down below this. */
  readonly floor: Readonly<Record<FilingStatus, number>>;
}

/** § 164(b)(6), with enough detail to explain the number. */
export interface SaltDeductionResult {
  readonly year: number;
  readonly filingStatus: FilingStatus;
  readonly stateAndLocalTaxesPaid: number;
  /**
   * AGI increased by income excluded under § 911, § 931 or § 933 — the same
   * definition Schedule 1-A uses.
   */
  readonly modifiedAdjustedGrossIncome: number;
  /** The statutory cap before the phase-down. */
  readonly statutoryCap: number;
  readonly phaseDownThreshold: number;
  readonly excessIncome: number;
  readonly phaseDownReduction: number;
  readonly floor: number;
  /** The cap actually applied: `statutoryCap - phaseDownReduction`, floored. */
  readonly cap: number;
  readonly deduction: number;
  readonly limitedByCap: boolean;
}

/**
 * Section 199A — the qualified business income deduction.
 *
 * The three limitations all key off **taxable income computed without regard to
 * this deduction**, not AGI. Below {@link Section199AParameters.thresholdAmount}
 * none of them applies and the deduction is a flat 20% of QBI. Across the
 * {@link Section199AParameters.phaseInRange} above it, two things happen at once:
 * the W-2 wage / qualified property cap phases *in*, and a specified service
 * trade or business phases *out*. Above the top of the range the cap binds in
 * full and an SSTB is worth nothing at all.
 */
export interface Section199AParameters {
  /** 20% — § 199A(a)(2), and the same rate for REIT/PTP income under § 199A(b)(1)(B). */
  readonly deductionRate: number;
  /**
   * Taxable income (before this deduction) at which the limitations begin.
   *
   * Married filing separately is $25 *above* single, which looks like a typo and
   * is not: § 1(f)(7) rounds the inflation adjustment down to a multiple of $50
   * for most filers but to a multiple of $25 for a separate return, and in 2026
   * the unrounded figure falls between the two.
   */
  readonly thresholdAmount: Readonly<Record<FilingStatus, number>>;
  /**
   * Width of the phase-in range above the threshold.
   *
   * OBBBA § 70105(b) widened this from $50,000/$100,000 to $75,000/$150,000
   * effective for tax years beginning after 2025, so 2026 is the first year the
   * wider range applies.
   */
  readonly phaseInRange: Readonly<Record<FilingStatus, number>>;
  /** 50% of W-2 wages — § 199A(b)(2)(B)(i). */
  readonly w2WageRate: number;
  /** 25% of W-2 wages, used in the alternative cap — § 199A(b)(2)(B)(ii). */
  readonly w2WageAlternativeRate: number;
  /** 2.5% of UBIA of qualified property, used in the alternative cap. */
  readonly qualifiedPropertyRate: number;
  /**
   * § 199A(i), added by OBBBA § 70105(c) and first effective in 2026: a floor
   * under the deduction for filers with real, actively conducted business income.
   *
   * `null` in a year where no floor applies.
   */
  readonly minimumDeduction: {
    /** The floor itself. Inflation-adjusted in $5 increments after 2026. */
    readonly amount: number;
    /**
     * Aggregate QBI from *active* qualified trades or businesses — ones in which
     * the taxpayer materially participates within the meaning of § 469(h) —
     * required before the floor applies.
     */
    readonly activeQualifiedBusinessIncomeFloor: number;
  } | null;
}

/**
 * The § 24 child tax credit, the § 24(h)(4) credit for other dependents, and the
 * § 24(d) refundable portion (the "additional child tax credit").
 *
 * OBBBA § 70104 made the credit permanent at $2,200 and indexed it for inflation
 * after 2025. The phase-out thresholds are **not** indexed — $200,000, or
 * $400,000 on a joint return, is the statutory figure and stays there.
 *
 * The phase-out rounds the excess *up* to a whole $1,000 before applying the
 * $50, which Schedule 8812 states as "if more than zero and not a multiple of
 * $1,000, increase to the next multiple of $1,000". That is the same "or
 * fraction thereof" rule as the § 163(h)(4) vehicle loan interest deduction, and
 * it means a filer one dollar over the threshold loses a full $50.
 */
export interface ChildTaxCreditParameters {
  /** Credit per qualifying child — $2,200 for 2026 under § 24(h)(2). */
  readonly amountPerChild: number;
  /** § 24(h)(4): $500 per dependent who is not a qualifying child. Not indexed. */
  readonly amountPerOtherDependent: number;
  /** A qualifying child must be *under* this age at the close of the year — § 24(c)(1). */
  readonly maximumChildAge: number;
  /**
   * The phase-out, expressed the way § 24(b)(1) does: $50 for each $1,000 "or
   * fraction thereof", so `rounding` is always `'up'` here.
   */
  readonly phaseOut: SteppedPhaseOut;
  readonly refundable: {
    /** § 24(d)(1)(A): the refundable portion cannot exceed this per qualifying child. */
    readonly maximumPerChild: number;
    /** § 24(d)(1)(B)(i): 15% of earned income above the threshold. */
    readonly phaseInRate: number;
    /** Earned income below this produces no refundable credit at all. */
    readonly phaseInThreshold: number;
    /**
     * § 24(d)(1)(B)(ii): with at least this many qualifying children the filer
     * may instead use social security taxes paid less the EITC, which is often
     * larger for a family whose earnings are mostly below the 15% phase-in.
     */
    readonly minimumChildrenForSocialSecurityAlternative: number;
  };
  /**
   * OBBBA § 70104(c), first effective 2025: the *taxpayer* must have a social
   * security number valid for employment, not merely the child. On a joint
   * return one spouse having one is enough.
   */
  readonly requiresTaxpayerSocialSecurityNumber: boolean;
}

/**
 * One row of the § 32 earned income credit table, keyed by number of qualifying
 * children (0, 1, 2, or 3+).
 *
 * `phaseOutStart` is given per filing status rather than as an unmarried figure
 * plus a single joint add-on, because the two are **not** offset by a constant.
 * § 32(b)(2)(B) adds an inflation-adjusted amount for a joint return and the IRS
 * rounds the resulting sum to the nearest $10, so the effective add-on differs
 * between the childless table and the with-children tables — $7,280 versus
 * $7,270 in 2026, and $7,110 versus $7,120 in 2025, which is the *opposite*
 * direction. Storing one add-on gets one of the two tables wrong by $10 of
 * income, and $10 of income at a 21.06% phase-out rate is $2.11 of credit.
 */
export interface EarnedIncomeCreditRow {
  /** § 32(b)(1) credit percentage: 7.65% / 34% / 40% / 45%. */
  readonly creditRate: number;
  /** § 32(b)(1) phase-out percentage: 7.65% / 15.98% / 21.06% / 21.06%. */
  readonly phaseOutRate: number;
  /** The maximum credit — the credit percentage applied to the earned income amount. */
  readonly maximumCredit: number;
  /** Where the phase-out begins, by filing status. */
  readonly phaseOutStart: Readonly<Record<FilingStatus, number>>;
}

/** § 32, the earned income credit. */
export interface EarnedIncomeCreditParameters {
  /**
   * Indexed by number of qualifying children, capped at 3. Four rows: 0, 1, 2,
   * and 3-or-more.
   */
  readonly table: readonly EarnedIncomeCreditRow[];
  /** § 32(i): disqualified investment income above this bars the credit outright. */
  readonly maximumInvestmentIncome: number;
  /** § 32(c)(1)(A)(ii)(II): age limits that apply only when there are no qualifying children. */
  readonly childlessAgeRange: {
    readonly minimum: number;
    readonly maximum: number;
  };
}

export interface YearParameters {
  readonly year: number;
  readonly ordinaryBrackets: Readonly<Record<FilingStatus, readonly Bracket[]>>;
  readonly standardDeduction: Readonly<Record<FilingStatus, number>>;
  /** Extra standard deduction *per qualifying condition* (age 65+, blind). */
  readonly additionalStandardDeduction: Readonly<Record<FilingStatus, number>>;
  readonly socialSecurityWageBase: number;
  readonly rates: {
    readonly socialSecurityEmployee: number;
    readonly socialSecurityEmployer: number;
    readonly medicareEmployee: number;
    readonly medicareEmployer: number;
    readonly additionalMedicare: number;
    readonly seSocialSecurity: number;
    readonly seMedicare: number;
  };
  readonly additionalMedicareThreshold: Readonly<Record<FilingStatus, number>>;
  /** Portion of net profit subject to SE tax (92.35%). */
  readonly seNetEarningsFactor: number;
  /** Net earnings below this produce no SE tax. */
  readonly seMinimumNetEarnings: number;
  readonly longTermCapitalGains: Readonly<Record<FilingStatus, readonly Bracket[]>>;
  readonly niit: {
    readonly rate: number;
    readonly thresholds: Readonly<Record<FilingStatus, number>>;
  };
  /** OBBBA temporary deductions, or `null` in a year where none are in effect. */
  readonly scheduleOneA: ScheduleOneAParameters | null;
  /** Section 199A qualified business income deduction. */
  readonly section199A: Section199AParameters;
  /** The § 164(b)(6) state and local tax cap. */
  readonly saltCap: SaltCapParameters;
  /** § 24 child tax credit, credit for other dependents, and the refundable portion. */
  readonly childTaxCredit: ChildTaxCreditParameters;
  /** § 32 earned income credit. */
  readonly earnedIncomeCredit: EarnedIncomeCreditParameters;
  readonly sources: readonly Citation[];
}

/** One trade or business, as § 199A sees it. */
export interface QualifiedBusiness {
  /** Label carried through to the result, purely for reporting. */
  readonly name?: string;
  /**
   * Qualified business income for the year, which may be negative.
   *
   * This is net of the deductions attributable to the business, including the
   * deductible half of self-employment tax, self-employed health insurance and
   * self-employed retirement contributions. It excludes wages paid to the owner
   * by an S corporation, guaranteed payments, capital gain, and investment income.
   */
  readonly qualifiedBusinessIncome: number;
  /** W-2 wages paid by the business and allocable to its QBI — § 199A(b)(4). */
  readonly w2Wages?: number;
  /**
   * Unadjusted basis immediately after acquisition of qualified property still
   * within its depreciable period — the "UBIA" in § 199A(b)(2)(B)(ii).
   */
  readonly unadjustedBasisOfQualifiedProperty?: number;
  /**
   * A specified service trade or business under § 199A(d)(2): health, law,
   * accounting, actuarial science, performing arts, consulting, athletics,
   * financial services, brokerage, investing, trading, dealing in securities,
   * and any business whose principal asset is the reputation or skill of its
   * employees or owners. Engineering and architecture are deliberately excluded.
   *
   * Below the threshold this flag changes nothing.
   */
  readonly isSpecifiedServiceTradeOrBusiness?: boolean;
  /**
   * Whether the taxpayer materially participates within the meaning of § 469(h).
   *
   * Used only by the § 199A(i) minimum deduction, which counts QBI from
   * *active* trades or businesses. Defaults to `true`, which is the ordinary
   * case for a sole proprietorship or an owner-operated pass-through.
   */
  readonly materiallyParticipates?: boolean;
}

/** How one trade or business contributed to the deduction. */
export interface QbiBusinessDetail {
  readonly name: string;
  /** QBI exactly as supplied. */
  readonly qualifiedBusinessIncome: number;
  readonly isSpecifiedServiceTradeOrBusiness: boolean;
  /**
   * The fraction of this business that counts. Always 1 for a non-SSTB and for
   * every business below the threshold; between 0 and 1 for an SSTB inside the
   * phase-in range; 0 for an SSTB above it.
   */
  readonly applicablePercentage: number;
  /** QBI after the SSTB applicable percentage — Schedule A (Form 8995-A) line 11. */
  readonly includedQualifiedBusinessIncome: number;
  /** W-2 wages after the SSTB applicable percentage. */
  readonly includedW2Wages: number;
  /** UBIA after the SSTB applicable percentage. */
  readonly includedQualifiedProperty: number;
  /** QBI after losses from other businesses have been netted against it. */
  readonly netQualifiedBusinessIncome: number;
  /** 20% of {@link netQualifiedBusinessIncome} — the deduction before any cap. */
  readonly tentativeDeduction: number;
  /** `max(50% of W-2 wages, 25% of W-2 wages + 2.5% of UBIA)`. */
  readonly wageAndPropertyLimit: number;
  /** How much the phasing-in wage cap took away. */
  readonly phaseInReduction: number;
  /** This business's share of the QBI component. */
  readonly component: number;
}

/** Form 8995 / Form 8995-A in full. */
export interface QbiDeductionResult {
  readonly year: number;
  readonly filingStatus: FilingStatus;
  /**
   * Taxable income figured without this deduction — Form 1040 AGI less the
   * standard or itemized deduction *and* less the Schedule 1-A total on line 13b.
   */
  readonly taxableIncomeBeforeDeduction: number;
  readonly thresholdAmount: number;
  readonly phaseInRange: number;
  readonly excessOverThreshold: number;
  /** 0 below the threshold, 1 at or above the top of the range. */
  readonly reductionRatio: number;
  /** `1 - reductionRatio`. The share of an SSTB that still counts. */
  readonly applicablePercentage: number;
  readonly businesses: readonly QbiBusinessDetail[];
  /** Form 8995-A line 16. */
  readonly qbiComponent: number;
  /** 20% of qualified REIT dividends and PTP income, with no wage or UBIA cap. */
  readonly reitPtpComponent: number;
  /** `qbiComponent + reitPtpComponent` — § 199A(b)(1). */
  readonly combinedQualifiedBusinessIncomeAmount: number;
  /** 20% of (taxable income before this deduction, less net capital gain). */
  readonly taxableIncomeLimit: number;
  readonly limitedByTaxableIncome: boolean;
  /** The § 199A(i) floor, or 0 when it does not apply. */
  readonly minimumDeduction: number;
  readonly appliedMinimumDeduction: boolean;
  readonly deduction: number;
  /**
   * Negative QBI carried into next year, as a non-positive number.
   *
   * A business loss does not produce a refundable benefit; it suppresses the
   * deduction this year and reduces QBI next year.
   */
  readonly qualifiedBusinessNetLossCarryforward: number;
  /** Negative REIT/PTP income carried into next year, as a non-positive number. */
  readonly reitPtpLossCarryforward: number;
}

/** Schedule 8812 (Form 1040) in full. */
export interface ChildTaxCreditResult {
  readonly year: number;
  readonly filingStatus: FilingStatus;
  readonly qualifyingChildren: number;
  readonly otherDependents: number;
  /** AGI increased by income excluded under § 911, § 931 or § 933 — Schedule 8812 line 3. */
  readonly modifiedAdjustedGrossIncome: number;
  /** `amountPerChild x qualifyingChildren`, before the phase-out. */
  readonly childCredit: number;
  /** `amountPerOtherDependent x otherDependents`, before the phase-out. */
  readonly otherDependentCredit: number;
  /** `childCredit + otherDependentCredit` — Schedule 8812 line 8. */
  readonly maximumCredit: number;
  readonly phaseOutThreshold: number;
  /** MAGI over the threshold, *before* it is rounded up to a whole $1,000. */
  readonly excessIncome: number;
  /**
   * The phase-out reduction. The excess is rounded up to a whole $1,000 first,
   * so this is always a multiple of $50 and a filer $1 over the threshold loses
   * the full $50.
   */
  readonly phaseOutReduction: number;
  /** `maximumCredit - phaseOutReduction`, floored at zero — Schedule 8812 line 12. */
  readonly creditAfterPhaseOut: number;
  /**
   * Income tax against which the non-refundable credit is limited.
   *
   * This is the § 26(a) *regular tax liability* — ordinary income tax plus the
   * tax on long-term capital gains. It deliberately excludes self-employment
   * tax, Net Investment Income Tax and Additional Medicare Tax: those are not
   * chapter 1 subchapter A liabilities and a non-refundable credit cannot reach
   * them.
   */
  readonly limitingTaxLiability: number;
  /** `min(creditAfterPhaseOut, limitingTaxLiability)` — the part that offsets tax. */
  readonly nonRefundableCredit: number;
  /** Earned income for § 32 purposes, which drives the 15% phase-in. */
  readonly earnedIncome: number;
  /** 15% of earned income above $2,500 — Schedule 8812 line 20. */
  readonly refundablePhaseIn: number;
  /**
   * § 24(d)(1)(B)(ii): social security taxes paid less the EITC, available only
   * with three or more qualifying children. `null` when it does not apply.
   */
  readonly socialSecurityAlternative: number | null;
  /** `maximumPerChild x qualifyingChildren` — the ceiling on the refundable part. */
  readonly refundableCap: number;
  /** The additional child tax credit — Schedule 8812 line 27. */
  readonly refundableCredit: number;
  /**
   * Credit that is simply lost: neither used against tax nor refunded.
   *
   * Non-zero for a filer whose tax liability is too small to absorb the
   * non-refundable part and whose earned income is too low to phase in the
   * refundable part. The credit for other dependents is never refundable, so it
   * lands here whenever tax liability runs out.
   */
  readonly unusedCredit: number;
}

/** § 32 in full, including why the credit is zero when it is. */
export interface EarnedIncomeCreditResult {
  readonly year: number;
  readonly filingStatus: FilingStatus;
  readonly qualifyingChildren: number;
  /**
   * Earned income under § 32(c)(2): wages plus net earnings from
   * self-employment, the latter **reduced by** the § 164(f) deduction for one
   * half of self-employment tax.
   */
  readonly earnedIncome: number;
  readonly adjustedGrossIncome: number;
  readonly creditRate: number;
  readonly phaseOutRate: number;
  readonly maximumCredit: number;
  /** `min(maximumCredit, creditRate x earnedIncome)` — § 32(a)(1). */
  readonly phasedInCredit: number;
  readonly phaseOutStart: number;
  /**
   * The income the phase-out actually runs on: `max(earnedIncome, AGI)`.
   *
   * § 32(a)(2)(B) measures the excess over the phase-out amount using AGI "if
   * greater" than earned income, so a filer with investment losses or
   * above-the-line deductions cannot phase the credit back in by lowering AGI.
   */
  readonly phaseOutIncome: number;
  readonly phaseOutReduction: number;
  /** The income at or above which no credit is allowed, given this filing status. */
  readonly completedPhaseOut: number;
  /** Disqualified income tested against the § 32(i) limit. */
  readonly investmentIncome: number;
  readonly investmentIncomeLimit: number;
  /** Why the credit is zero, or `null` when the filer is eligible. */
  readonly ineligibleReason:
    | 'investmentIncomeTooHigh'
    | 'filingSeparately'
    | 'ageOutsideChildlessRange'
    | 'noEarnedIncome'
    | null;
  readonly credit: number;
}

/** Every credit this package models, and the two totals that matter. */
export interface CreditsResult {
  /** Schedule 8812, or `null` when no dependents were supplied. */
  readonly childTaxCredit: ChildTaxCreditResult | null;
  /** § 32, or `null` when the credit was not computed — see {@link EstimateInput.age}. */
  readonly earnedIncomeCredit: EarnedIncomeCreditResult | null;
  /** Credits that can only reduce income tax, never below zero. */
  readonly totalNonRefundable: number;
  /** Credits that are paid out even when they exceed the tax due. */
  readonly totalRefundable: number;
}

/** One part of Schedule 1-A, with enough detail to explain the number. */
export interface AdditionalDeductionPart {
  /** Deduction actually allowed, after the cap and the phase-out. */
  readonly deduction: number;
  /** The claimed amount after any statutory cap but before the phase-out. */
  readonly cappedAmount: number;
  /** Amount by which the phase-out reduced `cappedAmount`. */
  readonly phaseOutReduction: number;
  /** MAGI in excess of this part's phase-out threshold. */
  readonly excessIncome: number;
  /** True when the filer is barred outright (filing status, age, or year). */
  readonly ineligible: boolean;
}

/** Schedule 1-A (Form 1040) in full. */
export interface AdditionalDeductionsResult {
  readonly year: number;
  readonly modifiedAdjustedGrossIncome: number;
  readonly tips: AdditionalDeductionPart;
  readonly overtime: AdditionalDeductionPart;
  readonly senior: AdditionalDeductionPart;
  readonly vehicleLoanInterest: AdditionalDeductionPart;
  /** Form 1040 line 13b. */
  readonly total: number;
}
